@extends('frontend.layouts.app')
@section('title', 'Home')
@section('content')
    @include('frontend.components.hero-area')
    @include('frontend.components.about-area')
    @include('frontend.components.feature-area')
    @include('frontend.components.experience-and-skills-area')
    @include('frontend.components.portfolio-area')
    @include('frontend.components.client-area')
    @include('frontend.components.counter-up-area')
    @include('frontend.components.award-area')
    @include('frontend.components.social-link-area')
    @include('frontend.components.call-to-action-area')
@endsection
